export const radarListing = [
    {label: "AL: BIRMINGHAM", value: "KBMX"},
    {label: "AL: HUNTSVILLE", value: "KHTX"},
    {label: "AL: MOBILE", value: "KMOB"},
    {label: "AR: LITTLE ROCK", value: "KLZK"},
    {label: "CO: DENVER/BOULDER", value: "KFTG"},
    {label: "CO: GRAND JUNCTION", value: "KGJT"},
    {label: "CO: PUEBLO", value: "KPUX"},
    {label: "FL: JACKSONVILLE", value: "KVAX"},
    {label: "FL: KEY WEST", value: "KBYX"},
    {label: "FL: MELBOURNE", value: "KMLB"},
    {label: "FL: MIAMI", value: "KAMX"},
    {label: "FL: TALLAHASSEE", value: "KTLH"},
    {label: "FL: TAMPA BAY AREA", value: "KTBW"},
    {label: "GA: PEACHTREE CITY/ATLANTA", value: "KFFC"},
    {label: "IA: DES MOINES", value: "KDMX"},
    {label: "IA: QUAD CITIES", value: "KDVN"},
    {label: "IA: SIOUX FALLS", value: "KFSD"},
    {label: "IL: CHICAGO", value: "KLOT"},
    {label: "IL: LINCOLN/CENTRAL ILLINOIS", value: "KILX"},
    {label: "IN: INDIANAPOLIS", value: "KIND"},
    {label: "IN: N. WEBSTER/NORTHERN", value: "KIWX"},
    {label: "KS: DODGE CITY", value: "KDDC"},
    {label: "KS: GOODLAND", value: "KGLD"},
    {label: "KS: TOPEKA", value: "KTWX"},
    {label: "KS: WICHITA", value: "KICT"},
    {label: "KY: JACKSON", value: "KJKL"},
    {label: "KY: LOUISVILLE", value: "KLVX"},
    {label: "KY: PADUCAH (1)", value: "KPAH"},
    {label: "KY: PADUCAH (2)", value: "KVWX"},
    {label: "LA: LAKE CHARLES", value: "KLCH"},
    {label: "LA: NEW ORLEANS/SLIDELL", value: "KLIX"},
    {label: "LA: SHREVEPORT", value: "KSHV"},
    {label: "MA: BOSTON /TAUNTON", value: "KBOX"},
    {label: "ME: CARIBOU", value: "KCBW"},
    {label: "ME: PORTLAND", value: "KGYX"},
    {label: "MI: DETROIT", value: "KDTX"},
    {label: "MI: GAYLORD/ALPENA", value: "KAPX"},
    {label: "MI: GRAND RAPIDS", value: "KGRR"},
    {label: "MI: MARQUETTE", value: "KMQT"},
    {label: "MN: DULUTH", value: "KDLH"},
    {label: "MN: MINNEAPOLIS", value: "KMPX"},
    {label: "MO: PLEASANT HILL", value: "KEAX"},
    {label: "MO: SPRINGFIELD", value: "KSGF"},
    {label: "MO: ST. LOUIS", value: "KLSX"},
    {label: "MS: JACKSON", value: "KDGX"},
    {label: "NC: MOREHEAD CITY", value: "KMHX"},
    {label: "NC: RALEIGH/DURHAM", value: "KRAX"},
    {label: "NC: WILMINGTON", value: "KLTX"},
    {label: "ND: BISMARCK", value: "KMBX"},
    {label: "ND: FARGO/GRAND FORKS", value: "KMVX"},
    {label: "NE: HASTINGS", value: "KUEX"},
    {label: "NE: NORTH PLATTE", value: "KLNX"},
    {label: "NE: OMAHA", value: "KOAX"},
    {label: "NM: ALBUQUERQUE", value: "KABX"},
    {label: "NY: ALBANY", value: "KENX"},
    {label: "NY: BINGHAMTON", value: "KBGM"},
    {label: "NY: BUFFALO", value: "KBUF"},
    {label: "NY: NEW YORK CITY", value: "KOKX"},
    {label: "OH: CLEVELAND", value: "KCLE"},
    {label: "OH: WILMINGTON/CINCINNATI", value: "KILN"},
    {label: "OK: NORMAN", value: "KTLX"},
    {label: "OK: TULSA", value: "KINX"},
    {label: "PA: MT HOLLY/PHILADELPHIA", value: "KDIX"},
    {label: "PA: PITTSBURGH", value: "KPBZ"},
    {label: "PA: STATE COLLEGE/CENTRAL", value: "KCCX"},
    {label: "SC: CHARLESTON", value: "KCLX"},
    {label: "SC: COLUMBIA", value: "KCAE"},
    {label: "SC: GREER/GREENVILLE/SPRTBG", value: "KGSP"},
    {label: "SD: ABERDEEN", value: "KABR"},
    {label: "SD: RAPID CITY", value: "KUDX"},
    {label: "TN: MEMPHIS", value: "KNQA"},
    {label: "TN: MORRISTOWN/KNOXVILLE", value: "KMRX"},
    {label: "TN: NASHVILLE", value: "KOHX"},
    {label: "TX: AMARILLO", value: "KAMA"},
    {label: "TX: AUSTIN/SANANTONIO", value: "KEWX"},
    {label: "TX: BROWNSVILLE", value: "KBRO"},
    {label: "TX: CORPUS CHRISTI", value: "KCRP"},
    {label: "TX: DALLAS / FT. WORTH", value: "KFWS"},
    {label: "TX: EL PASO", value: "KEPZ"},
    {label: "TX: HOUSTON/ GALVESTON", value: "KHGX"},
    {label: "TX: LUBBOCK", value: "KLBB"},
    {label: "TX: MIDLAND/ODESSA", value: "KMAF"},
    {label: "TX: SAN ANGELO", value: "KSJT"},
    {label: "VA: BLACKSBURG/ROANOKE", value: "KFCX"},
    {label: "VA: STERLING", value: "KLWX"},
    {label: "VA: WAKEFIELD", value: "KDOX"},
    {label: "VT: BURLINGTON", value: "KCXX"},
    {label: "WI: GREEN BAY", value: "KGRB"},
    {label: "WI: LA CROSSE", value: "KARX"},
    {label: "WI: MILWAUKEE", value: "KMKX"},
    {label: "WV: CHARLESTON", value: "KRLX"},
    {label: "WY: CHEYENNE", value: "KCYS"},
    {label: "WY: RIVERTON", value: "KRIW"}
]